# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fraudemailidentifier

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ secrets.AzureAppService_ContainerUsername_351411bce25c47b7a39b189f14a7d063 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4a10a9cf63d444c2b3b650cdca5ac35d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ vars.REGISTRY }}/${{ secrets.AzureAppService_ContainerUsername_351411bce25c47b7a39b189f14a7d063 }}/${{ vars.NAMESPACE }}/${{ vars.IMAGE }}:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fraudemailidentifier'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b79931368eef499294e3d448dafd5572 }}
        images: '${{ vars.REGISTRY }}/${{ secrets.AzureAppService_ContainerUsername_351411bce25c47b7a39b189f14a7d063 }}/${{ vars.NAMESPACE }}/${{ vars.IMAGE }}:${{ github.sha }}'